version: '3.0'

services:
  portainer:
    image: portainer/portainer-ce:2.9.2-alpine
    environmment:
    - TZ=Europe/Brussels
    - PGID=1000
    - PUID=1000
    command:
    - "-H unix:///var/run/docker.sock"
    ports:
    - 9000:9000
    volumes:
    - ${PORTAINER_FOLDER_DATA}:/data
    - ${PORTAINER_FOLDER_SHARED}:/shared
    - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission:2021.10.28
    environment:    
    - TZ=Europe/Brussels
    - PGID=1000
    - PUID=1000
    - USERNAME=${TRANSMISSION_USERNAME}
    - PASSWORD=${TRANSMISSION_PASSWORD}
    - HOME=/root
    ports:
    - 51413:51413
    - ${TRANMISSION_PORT}:9091
    restart: unless-stopped
    volumes:
    - ${TRANSMISSION_FOLDER_DEFAULT_DOWNLOAD}:/downloads
    - ${TRANSMISSION_FOLDER_TVSHOWS_DOWNLOAD}:/tvshows/downloads
    - ${TRANSMISSION_FOLDER_MOVIES_DOWNLOAD}:/movies/downloads
    - ${TRANSMISSION_FOLDER_CONFIG}:/config
    - ${TRANSMISSION_FOLDER_DATA}:/data
