version: '3.0'

services:

  transmission:
    image: linuxserver/transmission:2021.10.28
    environment:    
    - TZ=Europe/Brussels
    - PGID=1000
    - PUID=1000
    - USERNAME=${TRANSMISSION_USERNAME}
    - PASSWORD=${TRANSMISSION_PASSWORD}
    - HOME=/root
    ports:
    - 51413:51413
    - ${TRANSMISSION_PORT}:9091
    restart: unless-stopped
    volumes:
    - ${TRANSMISSION_FOLDER_DEFAULT_DOWNLOAD}:/downloads
    - ${TRANSMISSION_FOLDER_TVSHOWS_DOWNLOAD}:/tvshows/downloads
    - ${TRANSMISSION_FOLDER_MOVIES_DOWNLOAD}:/movies/downloads
    - ${TRANSMISSION_FOLDER_CONFIG}:/config
    - ${TRANSMISSION_FOLDER_DATA}:/data
