version: '3.0'

services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ${BAZARR_FOLDER_CONFIG}:/config:rw
      - ${BAZARR_FOLDER_MOVIES}:/movies:rw
      - ${BAZARR_FOLDER_TVSHOWS}:/tv:rw
      - ${BAZARR_FOLDER_MOVIES_DOWNLOADS}:/downloads/movies      - 
      - ${BAZARR_FOLDER_TVSHOWS_DOWNLOADS}:/downloads/series
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.bazarr_https_redirect.redirectscheme.permanent: "true"
      traefik.http.middlewares.bazarr_https_redirect.redirectscheme.scheme: https
      traefik.http.routers.bazarr_http.entrypoints: web
      traefik.http.routers.bazarr_http.middlewares: bazarr_https_redirect
      traefik.http.routers.bazarr_http.rule: Host(`bazarr.${DNS_HOSTNAME}`)
      traefik.http.routers.bazarr_https.entrypoints: websecure
      traefik.http.routers.bazarr_https.rule: Host(`bazarr.${DNS_HOSTNAME}`)
      traefik.http.routers.bazarr_https.tls.certresolver: myresolver
    ports:
      - ${BAZARR_PORT}:6767
    restart: unless-stopped
    logging:
      driver: loki:latest
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    depends_on:
      reverse-proxy:
        condition: service_started

  grafana:
    image: grafana/grafana-oss:8.3.3
    environment:
      - TZ=Europe/Brussels
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.grafana_https_redirect.redirectscheme.permanent: "true"
      traefik.http.middlewares.grafana_https_redirect.redirectscheme.scheme: https
      traefik.http.routers.grafana_http.entrypoints: web
      traefik.http.routers.grafana_http.middlewares: grafana_https_redirect
      traefik.http.routers.grafana_http.rule: Host(`grafana.${DNS_HOSTNAME}`)
      traefik.http.routers.grafana_https.entrypoints: websecure
      traefik.http.routers.grafana_https.rule: Host(`grafana.${DNS_HOSTNAME}`)
      traefik.http.routers.grafana_https.tls.certresolver: myresolver
    ports:
    - published: ${GRAFANA_PORT}
      target: 3000
    restart: unless-stopped
    user: root
    volumes:
    - ${GRAFANA_FOLDER_DATA}:/var/lib/grafana:rw    
    logging:
      driver: loki:latest
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    depends_on:
      reverse-proxy:
        condition: service_started

  heimdall:
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Brussels
    image: linuxserver/heimdall
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.heimdall_https_redirect.redirectscheme.permanent: "true"
      traefik.http.middlewares.heimdall_https_redirect.redirectscheme.scheme: https
      traefik.http.routers.heimdall_http.entrypoints: web
      traefik.http.routers.heimdall_http.middlewares: heimdall_https_redirect
      traefik.http.routers.heimdall_http.rule: Host(`heimdall.${DNS_HOSTNAME}`)
      traefik.http.routers.heimdall_https.entrypoints: websecure
      traefik.http.routers.heimdall_https.rule: Host(`heimdall.${DNS_HOSTNAME}`)
      traefik.http.routers.heimdall_https.tls.certresolver: myresolver
    ports:
    - published: ${HEIMDALL_PORT}
      target: 80
    restart: unless-stopped
    volumes:
    - ${HEIMDALL_FOLDER_CONFIG}:/config:rw    
    logging:
      driver: loki:latest
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    depends_on:
      reverse-proxy:
        condition: service_started

  homeassistant:
    image: homeassistant/home-assistant:stable
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Brussels
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.homeassistant_https_redirect.redirectscheme.permanent: "true"
      traefik.http.middlewares.homeassistant_https_redirect.redirectscheme.scheme: https
      traefik.http.routers.homeassistant_http.entrypoints: web
      traefik.http.routers.homeassistant_http.middlewares: homeassistant_https_redirect
      traefik.http.routers.homeassistant_http.rule: Host(`homeassistant.${DNS_HOSTNAME}`)
      traefik.http.routers.homeassistant_https.entrypoints: websecure
      traefik.http.routers.homeassistant_https.rule: Host(`homeassistant.${DNS_HOSTNAME}`)
      traefik.http.routers.homeassistant_https.tls.certresolver: myresolver
      traefik.http.services.homeassistant_https.loadbalancer.server.port: 8123
    logging:
      driver: loki:latest
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    ports:
    - published: ${HOMEASSISTANT_PORT}
      target: 8123
    - protocol: udp
      published: 5683
      target: 5683
    restart: unless-stopped
    volumes:
    - ${HOMEASSISTANT_FOLDER_CONFIG}:/config:rw
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
      reverse-proxy:
        condition: service_started
  
  radarr:
    depends_on:
      reverse-proxy:
        condition: service_started
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: Europe/Brussels
    image: linuxserver/radarr:latest
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.radarr_https_redirect.redirectscheme.permanent: "true"
      traefik.http.middlewares.radarr_https_redirect.redirectscheme.scheme: https
      traefik.http.routers.radarr_http.entrypoints: web
      traefik.http.routers.radarr_http.middlewares: radarr_https_redirect
      traefik.http.routers.radarr_http.rule: Host(`radarr.${DNS_HOSTNAME}`) || Host(`couchpotato.${DNS_HOSTNAME}`)
      traefik.http.routers.radarr_https.entrypoints: websecure
      traefik.http.routers.radarr_https.rule: Host(`radarr.${DNS_HOSTNAME}`) || Host(`couchpotato.${DNS_HOSTNAME}`)
      traefik.http.routers.radarr_https.tls.certresolver: myresolver    
    logging:
      driver: loki:latest
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    ports:
    - protocol: tcp
      published: ${RADARR_PORT}
      target: 7878
    restart: unless-stopped
    volumes:
    - ${RADARR_FOLDER_COMPLETED}:/completed:rw
    - ${RADARR_FOLDER_CONFIG}:/config:rw
    - ${RADARR_FOLDER_DOWNLOADS}:/downloads:rw
    - ${RADARR_FOLDER_MOVIES}:/movies:rw

  reverse-proxy:
    image: traefik:v2.9.1
    command: 
      --log.level=DEBUG 
      --api.insecure=true 
      --providers.docker 
      --providers.docker.exposedByDefault=false
      --entrypoints.web.address=:80 
      --entrypoints.websecure.address=:443 
      --certificatesresolvers.myresolver.acme.httpchallenge=true
      --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web 
      --certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}
      --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json 
      --metrics.prometheus=true
      --metrics.prometheus.addServicesLabels=true 
      --metrics.prometheus.addEntryPointsLabels=true    
    logging:
      driver: loki:latest
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"   
    restart: unless-stopped
    ports:
    - published: 80
      target: 80
    - published: 443
      target: 443
    - published: 8180
      target: 8080
    volumes:
    - ${TRAEFIK_FOLDER_LETSENCRYPT}:/letsencrypt:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro

  sickchill:
    image: linuxserver/sickchill:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.sickchill_https_redirect.redirectscheme.permanent: "true"
      traefik.http.middlewares.sickchill_https_redirect.redirectscheme.scheme: https
      traefik.http.routers.sickchill_http.entrypoints: web
      traefik.http.routers.sickchill_http.middlewares: sickchill_https_redirect
      traefik.http.routers.sickchill_http.rule: Host(`sickrage.${DNS_HOSTNAME}`) || Host(`sickchill.${DNS_HOSTNAME}`)
      traefik.http.routers.sickchill_https.entrypoints: websecure
      traefik.http.routers.sickchill_https.rule: Host(`sickrage.${DNS_HOSTNAME}`) || Host(`sickchill.${DNS_HOSTNAME}`)
      traefik.http.routers.sickchill_https.tls.certresolver: myresolver
    logging:
      driver: loki:latest
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    ports:
    - protocol: tcp
      published: ${SICKCHILL_PORT}
      target: 8081
    restart: unless-stopped
    volumes:
    - ${SICKCHILL_FOLDER_DOWNLOADS}:/tvshows/downloads:rw
    - ${SICKCHILL_FOLDER_TVSHOWS}:/series:rw
    - ${SICKCHILL_FOLDER_CONFIG}:/config:rw
    - ${SICKCHILL_FOLDER_DATA}:/data:rw
    depends_on:
      reverse-proxy:
        condition: service_started

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    group_add:
      - 109
    volumes:
      - ${JELLYFIN_FOLDER_CONFIG}:/config
      - ${JELLYFIN_FOLDER_CACHE}:/cache
      - ${RADARR_FOLDER_MOVIES}:/movies:ro
      - ${SICKCHILL_FOLDER_TVSHOWS}:/tvshows:ro
    devices:
    # Hardware encoding
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: "unless-stopped"
    ports:
      - 8096:8096
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.vnvie.ws
      
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.jellyfin_https_redirect.redirectscheme.permanent: "true"
      traefik.http.middlewares.jellyfin_https_redirect.redirectscheme.scheme: https
      traefik.http.routers.jellyfin_http.entrypoints: web
      traefik.http.routers.jellyfin_http.middlewares: jellyfin_https_redirect
      traefik.http.routers.jellyfin_http.rule: Host(`jellyfin.${DNS_HOSTNAME}`)
      traefik.http.routers.jellyfin_https.entrypoints: websecure
      traefik.http.routers.jellyfin_https.rule: Host(`jellyfin.${DNS_HOSTNAME}`)
      traefik.http.routers.jellyfin_https.tls.certresolver: myresolver
    depends_on:
      reverse-proxy:
        condition: service_started
        
  youtransfer:
    image: remie/youtransfer:stable
    container_name: youtransfer
    volumes:
      - ${YOUTRANSFER_UPLOADS}:/opt/youtransfer/uploads
      - ${YOUTRANSFER_CONFIG}:/opt/youtransfer/config
    restart: "unless-stopped"
    ports:
      - 8686:5000
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.youtransfer_https_redirect.redirectscheme.permanent: "true"
      traefik.http.middlewares.youtransfer_https_redirect.redirectscheme.scheme: https
      traefik.http.routers.youtransfer_http.entrypoints: web
      traefik.http.routers.youtransfer_http.middlewares: youtransfer_https_redirect
      traefik.http.routers.youtransfer_http.rule: Host(`youtransfer.${DNS_HOSTNAME}`)
      traefik.http.routers.youtransfer_https.entrypoints: websecure
      traefik.http.routers.youtransfer_https.rule: Host(`youtransfer.${DNS_HOSTNAME}`)
      traefik.http.routers.youtransfer_https.tls.certresolver: myresolver
    depends_on:
      reverse-proxy:
        condition: service_started
        
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: Dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - ${DASHY_CONFIG}:/app/public
    ports:
      - 4000:80
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    # Specify restart policy
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.dashy_https_redirect.redirectscheme.permanent: "true"
      traefik.http.middlewares.dashy_https_redirect.redirectscheme.scheme: https
      traefik.http.routers.dashy_http.entrypoints: web
      traefik.http.routers.dashy_http.middlewares: dashy_https_redirect
      traefik.http.routers.dashy_http.rule: Host(`dashy.${DNS_HOSTNAME}`)
      traefik.http.routers.dashy_https.entrypoints: websecure
      traefik.http.routers.dashy_https.rule: Host(`dashy.${DNS_HOSTNAME}`)
      traefik.http.routers.youtransfer_https.tls.certresolver: myresolver
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      reverse-proxy:
        condition: service_started
