version: '3.0'

services:

  transmission:
    image: linuxserver/transmission:4.0.4
    environment:    
    - TZ=Europe/Brussels
    - PGID=1000
    - PUID=1000
    - USERNAME=${TRANSMISSION_USERNAME}
    - PASSWORD=${TRANSMISSION_PASSWORD}
    - HOME=/root
    ports:
    - 51413:51413
    - 51413:51413/udp
    - ${TRANSMISSION_PORT}:9091
    restart: unless-stopped
    volumes:
    - ${TRANSMISSION_FOLDER_DEFAULT_DOWNLOAD}:/downloads
    - ${TRANSMISSION_FOLDER_TVSHOWS_DOWNLOAD}:/tvshows/downloads
    - ${TRANSMISSION_FOLDER_MOVIES_DOWNLOAD}:/movies/downloads
    - ${TRANSMISSION_FOLDER_CONFIG}:/config
    - ${TRANSMISSION_FOLDER_DATA}:/data  
    logging:
      driver: loki:latest
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
  adguard:
    image: adguard/adguardhome:latest
    ports:
    - 3030:3000
    - 53:53/tcp
    - 53:53/udp
    - 67:67/udp
    - 853:853
    - ${ADGUARD_PORT_HTTP}:80
    - ${ADGUARD_PORT_8053}:8053
    volumes:
    - ${ADGUARD_FOLDER_CONFIG}:/opt/adguardhome/conf
    - ${ADGUARD_FOLDER_WORK}:/opt/adguardhome/work
    restart: unless-stopped    
    logging:
      driver: loki:latest
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
    - 8883:1883
    - 1883:1883
    - 9001:9001
    volumes:
    - ${MOSQUITTO_FOLDER_CONFIG}:/mosquitto/config
    - ${MOSQUITTO_FOLDER_DATA}:/mosquitto/data
    - ${MOSQUITTO_FOLDER_LOG}:/mosquitto/log
    restart: unless-stopped    
    logging:
      driver: loki:latest
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        
  esphome:
    image: esphome/esphome:latest
    ports:
    - ${ESPHOME_PORT}:6052
    environment:
    - ESPHOME_DASHBOARD_USE_PING=true
    volumes:
    - ${ESPHOME_FOLDER_CONFIG}:/config
    - ${ESPHOME_FOLDER_LOCALTIME}:/etc/localtime
    restart: unless-stopped    
    logging:
      driver: loki:latest
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        
  node_red:
    image: nodered/node-red:2.1.4-1
    ports:
    - 1880:1880
    volumes:
    - ${NODERED_FOLDER_DATA}:/data
    restart: unless-stopped    
    logging:
      driver: loki:latest
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
  music-assistant:
    image: ghcr.io/music-assistant/server
    volumes:
        - ${MUSICASSISTANT_SERVER}:/data
    logging:
      driver: loki:latest
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
